version: "3.9"
services:
  gateway:
    image: nginx:alpine
    ports:
      - 80:80
      - 443:443
    networks:
      d2network:
        aliases:
          - proxy-name
    depends_on:
      - frontend
      - backend
    volumes:
      - E:\Data\proxy\nginx.conf:/etc/nginx/nginx.conf

  frontend:
    container_name: frontend
    build: 
      context: /d2frontend
    image: spongie/d2frontend:latest
    networks:
      d2network:
        aliases:
          - d2frontend
    expose:
      - "80"

  backend:
    container_name: backend
    build: 
      context: /RuneAPI
    image: spongie/d2runeapi:latest
    networks:
      d2network:
        aliases:
          - d2backend
    expose:
      - "80"
    environment:
      - RUNE_DB_PATH=/app/Data/runes.db
    volumes:
      - E:\Data:/app/Data

networks:
  d2network: