version: "3.9"
services:
  gateway:
    image: nginx:alpine
    ports:
      - 80:80
      - 443:443
    networks:
      d2network:
        aliases:
          - proxy-name
    depends_on:
      - frontend
      - backend
    volumes:
      - E:\tmp\nginx.conf:/etc/nginx/nginx.conf

  redis_cache:
    container_name: redis_cache
    image: redis:alpine
    volumes:
      - E:\tmp\redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      d2network: null
    ports:
      - "6379"

  frontend:
    container_name: frontend
    image: spongie/d2frontend:latest
    networks:
      d2network:
        aliases:
          - d2frontend
    expose:
      - "80"

  backend:
    container_name: backend
    image: spongie/d2runeapi:latest
    depends_on:
      - redis_cache
    networks:
      d2network:
        aliases:
          - d2backend
    expose:
      - "80"
    environment:
      - RUNE_DB_PATH=/app/Data/runes.db
      - REDIS_LOCATION=redis_cache
    volumes:
      - E:\tmp\:/app/Data

  authapi:
    container_name: authapi
    image: spongie/d2authapi:latest
    depends_on:
      - redis_cache
    networks:
      d2network:
        aliases:
          - d2authapi
    expose:
      - "80"
    environment:
      - AUTH_DB_PATH=/app/Data/auth.db
      - REDIS_LOCATION=redis_cache
    volumes:
      - E:\tmp\:/app/Data

networks:
  d2network: null
