version: "3.9"
services:
  gateway:
    image: nginx:alpine
    ports:
      - 80:80
      - 443:443
    networks:
      d2network:
        aliases:
          - proxy-name
    depends_on:
      - frontend
      - backend
    volumes:
      - /var/lib/d2data/nginx.conf:/etc/nginx/nginx.conf

  redis_cache:
    image: redis:alpine
    volumes:
      - /var/lib/d2data/redis.conf:/usr/local/etc/redis/redis.conf
    command:
      redis-server /usr/local/etc/redis/redis.conf
    networks:
      d2network:
    ports:
      - "6379"

  frontend:
    container_name: frontend
    image: spongie/d2frontend:latest
    networks:
      d2network:
        aliases:
          - d2frontend
    expose:
      - "80"

  backend:
    container_name: backend
    image: spongie/d2runeapi:latest
    networks:
      d2network:
        aliases:
          - d2backend
    expose:
      - "80"
    environment:
      - RUNE_DB_PATH=/app/Data/runes.db
      - REDIS_LOCATION=redis_cache
    volumes:
      - /var/lib/d2data:/app/Data

networks:
  d2network: