// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RuneAPI.Database;

namespace RuneAPI.Migrations
{
    [DbContext(typeof(RuneDbContext))]
    [Migration("20211028210052_AddRquiredLevel")]
    partial class AddRquiredLevel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("RuneAPI.Models.Modifier", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("RunewordId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "RunewordId" }, "IX_Modifier_RunewordId");

                    b.ToTable("Modifiers");
                });

            modelBuilder.Entity("RuneAPI.Models.Rune", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImagePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<long>("Number")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Runes");
                });

            modelBuilder.Entity("RuneAPI.Models.Runeword", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<long>("RequiredLevel")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TargetTypes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Runewords");
                });

            modelBuilder.Entity("RuneAPI.Models.RunewordRune", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("RuneId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("RunewordId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RuneId");

                    b.HasIndex("RunewordId");

                    b.ToTable("RunewordRunes");
                });

            modelBuilder.Entity("RuneAPI.Models.Modifier", b =>
                {
                    b.HasOne("RuneAPI.Models.Runeword", "Runeword")
                        .WithMany("Modifiers")
                        .HasForeignKey("RunewordId");

                    b.Navigation("Runeword");
                });

            modelBuilder.Entity("RuneAPI.Models.RunewordRune", b =>
                {
                    b.HasOne("RuneAPI.Models.Rune", "Rune")
                        .WithMany("RunewordRunes")
                        .HasForeignKey("RuneId");

                    b.HasOne("RuneAPI.Models.Runeword", "Runeword")
                        .WithMany("RunewordRunes")
                        .HasForeignKey("RunewordId");

                    b.Navigation("Rune");

                    b.Navigation("Runeword");
                });

            modelBuilder.Entity("RuneAPI.Models.Rune", b =>
                {
                    b.Navigation("RunewordRunes");
                });

            modelBuilder.Entity("RuneAPI.Models.Runeword", b =>
                {
                    b.Navigation("Modifiers");

                    b.Navigation("RunewordRunes");
                });
#pragma warning restore 612, 618
        }
    }
}
