// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RuneAPI.Database;

namespace RuneAPI.Migrations
{
    [DbContext(typeof(RuneDbContext))]
    [Migration("20211024085031_AddedImageColumn")]
    partial class AddedImageColumn
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("RuneAPI.Models.Modifier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RunewordId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RunewordId");

                    b.ToTable("Modifier");
                });

            modelBuilder.Entity("RuneAPI.Models.Rune", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImagePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Runes");
                });

            modelBuilder.Entity("RuneAPI.Models.Runeword", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("TargetTypes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Runewords");
                });

            modelBuilder.Entity("RuneRuneword", b =>
                {
                    b.Property<int>("RUNEWORDSId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RunesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("RUNEWORDSId", "RunesId");

                    b.HasIndex("RunesId");

                    b.ToTable("RuneRuneword");
                });

            modelBuilder.Entity("RuneAPI.Models.Modifier", b =>
                {
                    b.HasOne("RuneAPI.Models.Runeword", null)
                        .WithMany("Modifiers")
                        .HasForeignKey("RunewordId");
                });

            modelBuilder.Entity("RuneRuneword", b =>
                {
                    b.HasOne("RuneAPI.Models.Runeword", null)
                        .WithMany()
                        .HasForeignKey("RUNEWORDSId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RuneAPI.Models.Rune", null)
                        .WithMany()
                        .HasForeignKey("RunesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RuneAPI.Models.Runeword", b =>
                {
                    b.Navigation("Modifiers");
                });
#pragma warning restore 612, 618
        }
    }
}
